name: Cerritos Beach Properties
favicon: null
layout_spectrum: 0.4944324493408203
typography_spectrum: 0.7833051444031298
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ADD7F6'
    - '#87BFFF'
    - '#3F8EFC'
    - '#2667FF'
    - '#3B28CC'
  brandStrength: 0.9390673765446991
  lightness: 0.4023266800213605
  saturation: 0.9659310167189687
  rhythmicContrast: 0.7767291469499469
purpose: []
